feat: teams ui
DarkPhoenix2704/fossfolio pull request #102
Opened 2023-09-18 11:03 UTC by Surya-n

2023-09-18 11:05 UTC, DarkPhoenix2704 commented
@Surya-n If it is UI change, include screenshots

2023-09-18 17:14 UTC, Surya-n commented
![Screenshot 2023-09-18 223803](https://github.com/DarkPhoenix2704/fossfolio/assets/90127709/6e5bcda2-7cbc-4de7-975a-fddae8948f7a)

2023-09-18 21:43 UTC, DarkPhoenix2704 commented
Good job

2023-09-19 03:08 UTC, sreehari2003 commented on apps/web/pages/org/[id]/teams.tsx
> +    <div className="flex flex-wrap flex-col gap-y-[25px] gap-x-[75px] justify-center items-center p-4  md:justify-start lg:flex-row lg:items-center mr-6 ml-6 ">
use radix or shadcb ui input dont use default input

2023-09-19 03:08 UTC, sreehari2003 commented on apps/web/pages/org/[id]/teams.tsx
> +    className="block w-sm text-[16px] py-2 px-3 rounded-lg border border-gray-300 shadow-sm focus:ring focus:ring-brand-pink-100  focus:border-brand-blue-400 mt-4"
please run the linter

2023-09-19 03:08 UTC, sreehari2003 commented on apps/web/theme/style.css
> -}
what is this ?

2023-09-19 03:09 UTC, sreehari2003 commented on apps/web/views/dashboard/components/Teams.tsx
> +    </CardContent>
there should be spacing b/w easch user give a gap

2023-09-19 03:10 UTC, sreehari2003 commented on apps/web/pages/org/[id]/teams.tsx
> +              <h1 className="text-[30px] text-center font-bold">124</h1>
4px = 1 in tailwind border-3 border-[red]


so 38 px should be 9.5 ie make text-9.5

2023-09-19 12:50 UTC, Surya-n commented
![Ss](https://github.com/DarkPhoenix2704/fossfolio/assets/90127709/c1b91e7a-a3a4-4103-b9ea-46177476f9b4)

2023-09-20 04:04 UTC, DarkPhoenix2704 requested changes

2023-09-20 04:04 UTC, DarkPhoenix2704 commented on apps/web/views/dashboard/components/Teams.tsx
> +                        />
Add `object-cover` class to image

2023-09-21 05:45 UTC, merged