feat: added dnd and delete option in kanban
DarkPhoenix2704/fossfolio pull request #158
Opened 2024-05-31 09:52 UTC by sreehari2003

2024-05-31 10:32 UTC, DarkPhoenix2704 requested changes
Instead of cascade, this can be a series of manual operation. Using cascade can cause unexpected data loss in future

Also, if knex migration is still in plan, we can avoid this

2024-05-31 10:32 UTC, DarkPhoenix2704 commented on pnpm-lock.yaml
Revert this. You are downgrading the pnpm-lock file

2024-05-31 11:02 UTC, sreehari2003 commented on pnpm-lock.yaml
ok, can you do the Knex implementation? , we can incrementally migrate to knex.

2024-05-31 14:45 UTC, sreehari2003 commented on apps/web/views/tasks/Kanban.tsx
> +            if (item.id === id) return;
logic is wrong

2024-06-27 13:29 UTC, DarkPhoenix2704 commented
THis still needs to be merged?  @sreehari2003

2024-07-07 11:21 UTC, sreehari2003 commented
> THis still needs to be merged? @sreehari2003

no need

2024-07-07 11:21 UTC, closed without merging