fix: supertokens google oauth
DarkPhoenix2704/fossfolio pull request #33
Opened 2023-03-28 13:54 UTC by DarkPhoenix2704

Closes #23

2023-03-28 16:09 UTC, sreehari2003 reviewed
Frontend looks good , @reenphygeorge  need a review for backend

2023-03-29 18:56 UTC, reenphygeorge commented on .env
Make it fossfolio instead of postgres

2023-03-29 19:08 UTC, reenphygeorge requested changes

2023-03-29 19:08 UTC, reenphygeorge commented on apps/web/.env
this .env too ?

2023-03-29 19:08 UTC, reenphygeorge commented on apps/api/src/main.ts
Also it would be better to change the port from 8080 if we are integrating NocoDB as 8080 is the default port of Noco...

2023-03-31 14:14 UTC, DarkPhoenix2704 commented on apps/api/src/main.ts
We won't be using noco

2023-03-31 14:15 UTC, DarkPhoenix2704 commented on .env
ok

2023-03-31 18:57 UTC, closed without merging