Schema updated
DarkPhoenix2704/fossfolio pull request #42
Opened 2023-05-15 18:58 UTC by reenphygeorge

2023-05-16 01:06 UTC, DarkPhoenix2704 requested changes

2023-05-16 01:06 UTC, DarkPhoenix2704 commented on apps/api/prisma/schema.prisma
> +  organizationId      Organization[]
not id. This is organizations

2023-05-16 01:06 UTC, DarkPhoenix2704 commented on apps/api/prisma/schema.prisma
> +    memberId                User[]
Should be members

2023-05-16 01:06 UTC, DarkPhoenix2704 commented on apps/api/prisma/schema.prisma
> +    eventId                 Event[]
events

2023-05-16 01:06 UTC, DarkPhoenix2704 commented on apps/api/prisma/schema.prisma
> +  event     Event[]
Sponsors table should be mapped One-to-Many to event table

2023-06-04 17:03 UTC, sreehari2003 commented
> _ No description provided. _

@reenphygeorge  i think you should rebase this

2023-07-14 15:53 UTC, closed without merging