feat: added basic design for pricing card
DarkPhoenix2704/fossfolio pull request #55
Opened 2023-05-28 10:35 UTC by sreehari2003

2023-07-06 15:21 UTC, sreehari2003 commented on apps/web/pages/_app.tsx
@DarkPhoenix2704  @AshminJayson  instead of setting up the auth logic in layout i have added a auth provider wrapper to handle the auth state , leave code reviews when you get time . also since i changed the auth logic from layout i am facing issue to open the auth modal from home page using ref , i will be fixing the bug in next commits

2023-07-06 15:21 UTC, sreehari2003 commented on apps/web/pages/dashboard/[id]/teams.tsx
> +Page.RequireAuth = true;
now onwards we need to explicitly type the route protection of page this is a required field

2023-07-06 15:23 UTC, sreehari2003 commented on apps/web/layout/AuthProvider.tsx
@DarkPhoenix2704  do you think that is it a good idea to ssr the auth status instead of checkong the auth state using the redux thunk ? i have heard that redux dont work with ssr i might need to check on that!

2023-07-07 10:20 UTC, sreehari2003 commented on apps/web/layout/AuthProvider.tsx
> @DarkPhoenix2704 do you think that is it a good idea to ssr the auth status instead of checkong the auth state using the redux thunk ? i have heard that redux dont work with ssr i might need to check on that!

build completes on my local machine dont know y it is failing in dev environment

2023-07-16 02:31 UTC, DarkPhoenix2704 requested changes

2023-07-16 02:31 UTC, DarkPhoenix2704 commented on apps/api/src/event/dto/create-event.dto.ts
Remove this Dto.

2023-07-16 02:31 UTC, DarkPhoenix2704 commented on apps/api/src/event/event.controller.ts
this controller also

2023-07-16 02:31 UTC, DarkPhoenix2704 commented on apps/api/src/event/event.module.ts
this module also

2023-07-16 02:31 UTC, DarkPhoenix2704 commented on apps/web/.env.example
update .env.example

2023-07-16 14:34 UTC, DarkPhoenix2704 requested changes

2023-07-16 14:34 UTC, DarkPhoenix2704 commented on apps/web/.env.example
> +NEXT_PUBLIC_SUPABASE_PROJECT = ''
Remove this line

2023-07-17 01:14 UTC, merged