feat(rbac): casl
DarkPhoenix2704/fossfolio pull request #87
Opened 2023-08-18 19:12 UTC by sreehari2003

2023-08-19 02:52 UTC, DarkPhoenix2704 commented
The CASL is not needed. The existing RBAC is more than enough for our usage

2023-08-19 04:00 UTC, sreehari2003 commented
> The CASL is not needed. The existing RBAC is more than enough for our usage

I just like to ver engineer stuff

2023-08-19 04:16 UTC, DarkPhoenix2704 commented
Adding Complexity is Not Engineering

2023-08-28 02:34 UTC, DarkPhoenix2704 requested changes

2023-08-28 02:34 UTC, DarkPhoenix2704 commented on apps/api/src/org-invite/org-invite.service.ts
> +        const data = await this.prismaService.organization.update({
You can insert directly in Invite table, instead of from organization table

2023-08-28 02:34 UTC, DarkPhoenix2704 commented on apps/api/src/org-invite/org-invite.service.ts
> +        const inviteId = data.invites.find((el) => el.inviteeEmail === email).id;
You can get the invite from above insertion. Check Comment above

2023-08-28 02:34 UTC, DarkPhoenix2704 commented on apps/api/src/org-invite/sendEmail.ts
> +export const sendInvite = async (to:string,data:IData): Promise<boolean> => {
Use SMTP instead of Resend

2023-09-03 10:17 UTC, merged